### ISSUE TITLE
 Implementar buscador de productos por nombre.

### ISSUE THREAD

**Issue by NicolasJavierSosa** [NicolasJavierSosa/ProyectoIntegrador-POO2-2024#15]
_**Tipo:**_ Funcional
**_Prioridad:_** Media
**_Descripción:_** Proporcionar un buscador rápido y eficiente.

### Criterios de aceptación:
- [ ] Ofrecer sugerencias de productos mientras se escribe en el buscador.
- [x] Permitir búsquedas por nombre y mostrar resultados instantáneamente.

### Detalles de la tarea:
En la primer iteración nos centraremos más que nada en la búsqueda de los productos por nombre, y perfeccionaremos la funcionalidad en la segunda iteración

**Comment by BiancaMichelle** [comment]
_**Tipo:**_ Funcional
**_Prioridad:_** Media
**_Descripción:_** Proporcionar un buscador rápido y eficiente.

### Criterios de aceptación:
- [ ] Ofrecer sugerencias de productos mientras se escribe en el buscador.
- [x] Permitir búsquedas por nombre y mostrar resultados instantáneamente.

### Detalles de la tarea:
