### ISSUE TITLE
Implementar catálogo de productos en la página.

### ISSUE THREAD

**Issue by NicolasJavierSosa** [NicolasJavierSosa/ProyectoIntegrador-POO2-2024#20]
**_Tipo:_** Funcional
**_Prioridad:_** Alta
**_Descripción:_** Mostrar un catálogo de productos disponibles con imágenes, precios y descripciones.

### Criterios de aceptación:
- [x] El catálogo debe incluir imágenes, precios, y descripciones de los productos.

### Detalles de la tarea:
A cargo del diseño de la interfaz del catalogo estarán Lautaro y Nicolas, mientras que Hernán se encargará de la parte backend

**Comment by BiancaMichelle** [comment]
**_Tipo:_** Funcional
**_Prioridad:_** Alta
**_Descripción:_** Mostrar un catálogo de productos disponibles con imágenes, precios y descripciones.

### Criterios de aceptación:
El catálogo debe incluir imágenes, precios, y descripciones de los productos.

### Detalles de la tarea:
A cargo del diseño de la interfaz del catalogo estarán Lautaro y Nicolas, mientras que Hernán se encargará de la parte backend
